/*
 * Generates core/.../Help.kt from the website's own FAQ copy.
 *
 * The words users read in the app have to be the words on the site: two
 * hand-maintained copies of "do I pay on Qasda?" drift, and the one that
 * drifts is always the one nobody is looking at. So this reads
 * public/page-content.js out of the web repo and writes the Kotlin.
 *
 * Run it from the Android repo when the site's FAQ changes:
 *   node gen-help.js "C:/Users/you/Documents/tayaran-dz"
 */
const fs = require('fs');
const path = require('path');

const webRepo = process.argv[2] || 'C:/Users/Abderrahmane/Documents/tayaran-dz';
const P = require(path.join(webRepo, 'public', 'page-content.js'));

const unesc = (s) => s.replace(/&amp;/g, '&').replace(/&lt;/g, '<').replace(/&gt;/g, '>')
  .replace(/&quot;/g, '"').replace(/&#39;/g, "'");
const kt = (s) => '"' + s.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\$/g, '\\$') + '"';

function faqOf(lang) {
  const body = P.render('faq', lang).split('<div class="page-body">')[1];
  return body.split('<div class="faq-group">').slice(1).map((chunk) => {
    const title = unesc((chunk.match(/^<h2>(.*?)<\/h2>/) || [, ''])[1]);
    const qa = [];
    const itemRe = /<button class="faq-q"[^>]*><span>([\s\S]*?)<\/span>[\s\S]*?<div class="faq-a"[^>]*><p>([\s\S]*?)<\/p>/g;
    let m;
    while ((m = itemRe.exec(chunk)) !== null) qa.push([unesc(m[1]), unesc(m[2])]);
    return { title, qa };
  });
}

let body = '';
for (const [tag, konst] of Object.entries({ fr: 'FR', ar: 'AR', en: 'EN' })) {
  const groups = faqOf(tag);
  body += `        Lang.${konst} -> listOf(\n`;
  for (const g of groups) {
    body += `            HelpGroup(\n                ${kt(g.title)},\n                listOf(\n`;
    for (const [q, a] of g.qa) {
      body += `                    HelpEntry(\n                        ${kt(q)},\n                        ${kt(a)},\n                    ),\n`;
    }
    body += `                ),\n            ),\n`;
  }
  body += `        )\n`;
  console.error(`${tag}: ${groups.length} groups, ${groups.reduce((n, g) => n + g.qa.length, 0)} entries`);
}

const out = `package pro.qasdatrip.core

/**
 * The help pages, in the words the website already uses.
 *
 * GENERATED by gen-help.js in the repo root from public/page-content.js in
 * the web repo. Edit the copy there and run the generator; editing this file
 * by hand means the app and the site start answering "do I pay on Qasda?"
 * differently, and the one that drifts is the one nobody is looking at.
 *
 * It lives in core, and in the app rather than behind a fetch, because these
 * are the questions somebody asks when a booking has gone sideways - which is
 * exactly when they may have no signal.
 */
data class HelpEntry(val question: String, val answer: String)

data class HelpGroup(val title: String, val entries: List<HelpEntry>)

object Help {
    fun groups(lang: Lang): List<HelpGroup> = when (lang) {
${body}    }
}
`;

const dest = path.join(__dirname, 'core', 'src', 'commonMain', 'kotlin', 'pro', 'qasdatrip', 'core', 'Help.kt');
fs.writeFileSync(dest, out, 'utf8');
console.error('wrote ' + dest);
