package pro.qasdatrip.core

/**
 * The help pages, in the words the website already uses.
 *
 * GENERATED by gen-help.js in the repo root from public/page-content.js in
 * the web repo. Edit the copy there and run the generator; editing this file
 * by hand means the app and the site start answering "do I pay on Qasda?"
 * differently, and the one that drifts is the one nobody is looking at.
 *
 * It lives in core, and in the app rather than behind a fetch, because these
 * are the questions somebody asks when a booking has gone sideways - which is
 * exactly when they may have no signal.
 */
data class HelpEntry(val question: String, val answer: String)

data class HelpGroup(val title: String, val entries: List<HelpEntry>)

object Help {
    fun groups(lang: Lang): List<HelpGroup> = when (lang) {
        Lang.FR -> listOf(
            HelpGroup(
                "Réserver et payer",
                listOf(
                    HelpEntry(
                        "Est-ce que je paie sur Qasda ?",
                        "Non. Qasda compare les prix et vous redirige vers le site de réservation que vous choisissez. La réservation et le paiement se font entièrement chez lui.",
                    ),
                    HelpEntry(
                        "Qui émet mon billet ?",
                        "Le site de réservation sur lequel vous finalisez. C'est lui qui vous envoie la confirmation et le billet électronique.",
                    ),
                    HelpEntry(
                        "Quels moyens de paiement sont acceptés ?",
                        "Cela dépend du site : carte CIB, Edahabia, virement, ou paiement à la livraison du billet. Les moyens acceptés sont indiqués sur le site de réservation avant le paiement.",
                    ),
                    HelpEntry(
                        "J'ai déjà réservé et j'ai un problème.",
                        "Contactez directement le site de réservation qui a émis le billet. Qasda n'a pas accès à votre dossier et ne peut ni le modifier ni l'annuler.",
                    ),
                ),
            ),
            HelpGroup(
                "Les prix",
                listOf(
                    HelpEntry(
                        "Le prix a changé entre Qasda et le site. Pourquoi ?",
                        "Les tarifs aériens bougent en permanence et les places les moins chères partent vite. Le prix qui fait foi est celui affiché sur le site de réservation au moment du paiement.",
                    ),
                    HelpEntry(
                        "Est-ce que Qasda prend une commission sur mon billet ?",
                        "Non. Nous affichons le prix du site de réservation, sans supplément.",
                    ),
                    HelpEntry(
                        "Le prix affiché est-il par personne ?",
                        "Non. C'est le prix total pour tous les voyageurs de votre recherche.",
                    ),
                    HelpEntry(
                        "Les taxes sont-elles comprises ?",
                        "Oui, les prix affichés comprennent les taxes et frais obligatoires. Les options payantes — bagage supplémentaire, choix du siège — sont ajoutées sur le site de réservation.",
                    ),
                ),
            ),
            HelpGroup(
                "Vols et bagages",
                listOf(
                    HelpEntry(
                        "Le bagage en soute est-il inclus ?",
                        "Quand nous le savons, la carte du vol porte la mention « Bagage inclus ». Sans cette mention, vérifiez sur le site de réservation avant de payer.",
                    ),
                    HelpEntry(
                        "Que veut dire « 1 escale » sur un aller-retour ?",
                        "Nous comptons les escales sur le trajet le plus chargé. Un aller direct avec un retour à une escale est signalé « 1 escale », pour éviter la mauvaise surprise.",
                    ),
                    HelpEntry(
                        "Pourquoi ma destination n'apparaît pas ?",
                        "Nous couvrons les vols au départ d'Algérie. Si un trajet ne remonte pas, c'est qu'aucun site de réservation ne le propose à ces dates.",
                    ),
                ),
            ),
            HelpGroup(
                "Le service",
                listOf(
                    HelpEntry(
                        "Qasda est-il gratuit ?",
                        "Oui, entièrement, et sans compte à créer.",
                    ),
                    HelpEntry(
                        "Dans quelles langues ?",
                        "Français, arabe et anglais. Le sélecteur de langue est en haut de page.",
                    ),
                    HelpEntry(
                        "Faut-il créer un compte ?",
                        "Non. Qasda fonctionne sans inscription.",
                    ),
                ),
            ),
        )
        Lang.AR -> listOf(
            HelpGroup(
                "الحجز والدفع",
                listOf(
                    HelpEntry(
                        "هل أدفع على قصدة؟",
                        "لا. قصدة تقارن الأسعار وتنقلك إلى موقع الحجز الذي تختاره. الحجز والدفع يتمّان عنده بالكامل.",
                    ),
                    HelpEntry(
                        "من يصدر تذكرتي؟",
                        "موقع الحجز الذي تُتمّ عنده العملية. وهو الذي يرسل لك التأكيد والتذكرة الإلكترونية.",
                    ),
                    HelpEntry(
                        "ما وسائل الدفع المقبولة؟",
                        "حسب الموقع: بطاقة ⁦CIB⁩ أو الذهبية أو تحويل أو الدفع عند تسليم التذكرة. الوسائل المقبولة مذكورة على موقع الحجز قبل الدفع.",
                    ),
                    HelpEntry(
                        "حجزت بالفعل وواجهت مشكلة.",
                        "اتصل مباشرة بموقع الحجز الذي أصدر التذكرة. قصدة لا تملك أي وصول إلى ملفك ولا تستطيع تعديله أو إلغاءه.",
                    ),
                ),
            ),
            HelpGroup(
                "الأسعار",
                listOf(
                    HelpEntry(
                        "تغيّر السعر بين قصدة والموقع. لماذا؟",
                        "أسعار الطيران تتغير باستمرار والمقاعد الأرخص تنفد بسرعة. السعر المعتمد هو المعروض على موقع الحجز عند الدفع.",
                    ),
                    HelpEntry(
                        "هل تأخذ قصدة عمولة على تذكرتي؟",
                        "لا. نعرض سعر موقع الحجز، دون أي إضافة.",
                    ),
                    HelpEntry(
                        "هل السعر المعروض للشخص الواحد؟",
                        "لا. هو المجموع لكل المسافرين في بحثك.",
                    ),
                    HelpEntry(
                        "هل الرسوم مشمولة؟",
                        "نعم، الأسعار المعروضة تشمل الرسوم والضرائب الإلزامية. الخيارات المدفوعة — حقيبة إضافية أو اختيار المقعد — تُضاف على موقع الحجز.",
                    ),
                ),
            ),
            HelpGroup(
                "الرحلات والحقائب",
                listOf(
                    HelpEntry(
                        "هل الحقيبة في العنبر مشمولة؟",
                        "عندما نعرف ذلك، تحمل بطاقة الرحلة عبارة «مع حقيبة». في غياب هذه العبارة، تحقّق على موقع الحجز قبل الدفع.",
                    ),
                    HelpEntry(
                        "ماذا يعني «توقف واحد» في رحلة ذهاب وإياب؟",
                        "نحسب التوقفات على الشق الأكثر توقفًا. ذهاب مباشر مع عودة بتوقف واحد يظهر «توقف واحد»، تفاديًا للمفاجأة.",
                    ),
                    HelpEntry(
                        "لماذا لا تظهر وجهتي؟",
                        "نغطي الرحلات المنطلقة من الجزائر. إذا لم يظهر خط ما، فذلك لأن أي موقع حجز لا يعرضه في تلك التواريخ.",
                    ),
                ),
            ),
            HelpGroup(
                "الخدمة",
                listOf(
                    HelpEntry(
                        "هل قصدة مجانية؟",
                        "نعم، بالكامل، ودون إنشاء حساب.",
                    ),
                    HelpEntry(
                        "بأي لغات؟",
                        "الفرنسية والعربية والإنجليزية. مُبدّل اللغة في أعلى الصفحة.",
                    ),
                    HelpEntry(
                        "هل يجب إنشاء حساب؟",
                        "لا. قصدة تعمل دون تسجيل.",
                    ),
                ),
            ),
        )
        Lang.EN -> listOf(
            HelpGroup(
                "Booking and paying",
                listOf(
                    HelpEntry(
                        "Do I pay on Qasda?",
                        "No. Qasda compares prices and sends you to the booking site you choose. Booking and payment happen entirely there.",
                    ),
                    HelpEntry(
                        "Who issues my ticket?",
                        "The booking site where you complete the purchase. It also sends you the confirmation and the e-ticket.",
                    ),
                    HelpEntry(
                        "Which payment methods are accepted?",
                        "It depends on the site: CIB card, Edahabia, bank transfer, or cash on ticket delivery. The accepted methods are shown on the booking site before payment.",
                    ),
                    HelpEntry(
                        "I have already booked and something is wrong.",
                        "Contact the booking site that issued the ticket. Qasda has no access to your file and can neither change nor cancel it.",
                    ),
                ),
            ),
            HelpGroup(
                "Prices",
                listOf(
                    HelpEntry(
                        "The price changed between Qasda and the site. Why?",
                        "Air fares move constantly and the cheapest seats go fast. The price that stands is the one shown on the booking site at payment.",
                    ),
                    HelpEntry(
                        "Does Qasda take a commission on my ticket?",
                        "No. We show the booking site’s price, with nothing added.",
                    ),
                    HelpEntry(
                        "Is the price shown per person?",
                        "No. It is the total for every traveller in your search.",
                    ),
                    HelpEntry(
                        "Are taxes included?",
                        "Yes, the prices shown include taxes and mandatory charges. Paid options — extra baggage, seat selection — are added on the booking site.",
                    ),
                ),
            ),
            HelpGroup(
                "Flights and baggage",
                listOf(
                    HelpEntry(
                        "Is checked baggage included?",
                        "When we know, the flight card carries a \"Baggage included\" note. Without it, check on the booking site before paying.",
                    ),
                    HelpEntry(
                        "What does \"1 stop\" mean on a return trip?",
                        "We count stops on the busier leg. A direct outbound with a one-stop return is flagged \"1 stop\", so there is no surprise.",
                    ),
                    HelpEntry(
                        "Why is my destination missing?",
                        "We cover flights departing from Algeria. If a route does not appear, no booking site is offering it on those dates.",
                    ),
                ),
            ),
            HelpGroup(
                "The service",
                listOf(
                    HelpEntry(
                        "Is Qasda free?",
                        "Yes, entirely, and with no account to create.",
                    ),
                    HelpEntry(
                        "Which languages?",
                        "French, Arabic and English. The language switcher is at the top of the page.",
                    ),
                    HelpEntry(
                        "Do I need an account?",
                        "No. Qasda works without signing up.",
                    ),
                ),
            ),
        )
    }
}
