package pro.qasdatrip.core

/**
 * The words, in the three languages the product speaks. They live in the
 * shared module rather than in Android resources so the iOS app says exactly
 * the same things, and so a string can never exist in one language only.
 */
data class Words(
    val appName: String = "Qasda",
    val heroTitle: String,
    val heroSub: String,
    val from: String,
    val to: String,
    val dates: String,
    val travellers: String,
    val search: String,
    val roundTrip: String,
    val oneWay: String,
    val searching: String,
    val searchingSub: String,
    val resultsCount: String,       // {n}
    val cheapestOn: String,         // {site}
    val bagIncluded: String,
    val bagNone: String,
    val seatsShort: String,         // {n}
    val direct: String,
    val stopsOne: String,
    val stopsMany: String,          // {n}
    val outbound: String,
    val inbound: String,
    val book: String,
    val noResultsTitle: String,     // {from} {to}
    val noResultsSub: String,
    val failedTitle: String,
    val failedSub: String,
    val retry: String,
    val priceBySite: String,
    val cheapest: String,
    val economy: String,
    val searchCity: String,
    val noAirport: String,
    val chooseDates: String,
    val confirm: String,
    val cancel: String,
    val cabinBag: String,
    val checkedBag: String,
    val bagUnknown: String,
    val pieces: String,             // {n}
    val kilos: String,              // {n}
    val conditions: String,
    val refundable: String,
    val nonRefundable: String,
    val changeable: String,
    val nonChangeable: String,
    val feeApplies: String,         // {amount}
    val operatedBy: String,         // {airline}
    val adults: String,
    val adultsAge: String,
    val children: String,
    val childrenAge: String,
    val infants: String,
    val infantsAge: String,
    val cabinClass: String,
    val premium: String,
    val business: String,
    val first: String,
    val apply: String,
    val filters: String,
    val sortBy: String,
    val sortPrice: String,
    val sortDeparture: String,
    val sortDuration: String,
    val departureTime: String,
    val morning: String,
    val afternoon: String,
    val evening: String,
    val night: String,
    val maxPrice: String,
    val reset: String,
    val showCount: String,          // {n}
    val noMatchTitle: String,
    val noMatchSub: String,
    val stopsLabel: String,
    val navHome: String,
    val navHelp: String,
    val navSettings: String,
    val about: String,
    val language: String,
    val systemLanguage: String,
    val howItWorks: String,
    val privacy: String,
    val contactUs: String,
    val openOnSite: String,
    val version: String,
    val recentSearches: String,
    val offline: String,
    val seatOne: String,
    val edit: String,
    val priceCalendar: String,
    val calendarLoading: String,
    val calendarEmpty: String,
    val calendarNote: String,
    val cheapestDay: String,        // {date} {price}
    val noPriceThatDay: String,
    val nearbyDates: String,
    val comparing: String,
    val offersSoFar: String,        // {n}
    val aboutTitle: String,
    val aboutTagline: String,
    val aboutWhat: String,
    val aboutNotTickets: String,
    val readMore: String,
    val faq: String,
    val cheapestOfSites: String,    // {site} {n}
    val navTracking: String,
    val trackRoute: String,
    val trackTitle: String,
    val trackSub: String,
    val trackEmail: String,
    val trackEmailHint: String,
    val trackTarget: String,
    val trackTargetHint: String,
    val trackStart: String,
    val trackNoAccount: String,
    val trackSent: String,          // {email}
    val trackSentSub: String,
    val trackBadEmail: String,
    val trackFailed: String,
    val myTracking: String,
    val noTracking: String,
    val noTrackingSub: String,
    val openManageLink: String,
    val pasteManageLink: String,
    val linkNotValid: String,
    val stopTracking: String,
    val newTracking: String,
    val priceHistory: String,       // {n} days
    val historyLow: String,
    val historyAverage: String,
    val historyHigh: String,
    val historyObserved: String,    // {n}
    val historyThin: String,
    val historyNone: String,
    val seeTodayOffers: String,
    val whenYouSubscribed: String,  // {price}
    val targetSet: String,          // {price}
    val bestPrice: String,
    val seeOffer: String,
    val travellerOne: String,
    val travellersMany: String,     // {n}
    val airlineOne: String,
    val airlinesMany: String,       // {n}
    val compareSites: String,
    val bookOn: String,             // {site}
    val stopsTwoPlus: String,
    val baggage: String,
    val anyBaggage: String,
    val navAccount: String,
    val seeDetails: String,
    val sitesQuoting: String,       // {n}
    val onlyOnSite: String,         // {site}
    val thisDevice: String,
    val thisDeviceSub: String,
    val preferences: String,
    val helpAndInfo: String,
    val settingsAndAlerts: String,
    val settingsAndAlertsSub: String,
) {
    companion object {
        fun of(lang: Lang): Words = when (lang) {
            Lang.FR -> Words(
                heroTitle = "Tous les sites. Une recherche.",
                heroSub = "Qasda interroge les sites de réservation algériens en même temps.",
                from = "Départ", to = "Destination", dates = "Dates", travellers = "Voyageurs",
                search = "Rechercher", roundTrip = "Aller-retour", oneWay = "Aller simple",
                searching = "Nous cherchons le meilleur prix", searchingSub = "Quatre sites, en même temps.",
                resultsCount = "{n} vols", cheapestOn = "{site} · le moins cher",
                bagIncluded = "Bagage inclus", bagNone = "Sans bagage", seatsShort = "{n} places",
                direct = "Direct", stopsOne = "1 escale", stopsMany = "{n} escales",
                outbound = "Aller", inbound = "Retour", book = "Réserver",
                noResultsTitle = "Aucun vol {from} → {to}",
                noResultsSub = "Aucun site de réservation ne propose ce trajet à cette date.",
                failedTitle = "La recherche n’a pas abouti",
                failedSub = "La connexion s’est interrompue avant que les sites répondent.",
                retry = "Réessayer", priceBySite = "Le prix, site par site", cheapest = "le moins cher",
                economy = "Économique", searchCity = "Ville ou aéroport", noAirport = "Aucun aéroport ne correspond",
                chooseDates = "Choisir les dates", confirm = "Confirmer", cancel = "Annuler",
                cabinBag = "Bagage cabine", checkedBag = "Bagage en soute", bagUnknown = "Non communiqué",
                pieces = "{n} pièce(s)", kilos = "{n} kg", conditions = "Conditions du billet",
                refundable = "Remboursable", nonRefundable = "Non remboursable",
                changeable = "Modifiable", nonChangeable = "Non modifiable",
                feeApplies = "{amount} de frais", operatedBy = "Opéré par {airline}",
                adults = "Adultes", adultsAge = "12 ans et plus",
                children = "Enfants", childrenAge = "2 – 11 ans",
                infants = "Bébés", infantsAge = "moins de 2 ans",
                cabinClass = "Classe de cabine", premium = "Économique premium",
                business = "Affaires", first = "Première", apply = "Appliquer",
                filters = "Filtres", sortBy = "Trier", sortPrice = "Prix",
                sortDeparture = "Départ", sortDuration = "Durée",
                departureTime = "Heure de départ", morning = "Matin", afternoon = "Après-midi",
                evening = "Soir", night = "Nuit", maxPrice = "Prix maximum",
                reset = "Réinitialiser", showCount = "Voir {n} vols",
                noMatchTitle = "Aucun vol ne correspond",
                noMatchSub = "Élargissez les filtres pour voir plus de résultats.",
                stopsLabel = "Escales",
                navHome = "Accueil", navHelp = "Aide", navSettings = "Réglages",
                about = "À propos", language = "Langue",
                systemLanguage = "Langue du téléphone",
                howItWorks = "Comment ça marche", privacy = "Confidentialité",
                contactUs = "Nous écrire", openOnSite = "Ouvrir sur le site",
                version = "Version", recentSearches = "Recherches récentes",
                offline = "Pas de connexion internet",
                seatOne = "1 place", edit = "Modifier",
                priceCalendar = "Calendrier des prix",
                calendarLoading = "Nous interrogeons les sites pour chaque date. Cela prend un moment.",
                calendarEmpty = "Aucun prix pour cette période.",
                calendarNote = "Chaque prix est celui qu’un site a affiché pour cette date. Une date sans prix est une date qu’aucun site n’a cotée.",
                cheapestDay = "Le moins cher : {date} · {price}",
                noPriceThatDay = "Aucun prix",
                nearbyDates = "Dates proches",
                comparing = "Nous comparons les offres…",
                offersSoFar = "{n} offres",
                aboutTitle = "À propos",
                aboutTagline = "Le comparateur de vols au départ d’Algérie",
                aboutWhat = "Qasda interroge en direct les agences algériennes et affiche le prix réel de chaque offre, sans commission ni majoration.",
                aboutNotTickets = "Nous ne vendons pas de billets : la réservation se fait toujours sur le site de l’agence choisie.",
                readMore = "En savoir plus",
                faq = "Questions fréquentes",
                cheapestOfSites = "{site} · le moins cher des {n} sites",
                navTracking = "Suivi",
                trackRoute = "Suivre ce trajet",
                trackTitle = "Suivre ce trajet",
                trackSub = "Nous surveillons le prix pour vous.",
                trackEmail = "Votre adresse e-mail",
                trackEmailHint = "nom@exemple.com",
                trackTarget = "M’alerter en dessous de (facultatif)",
                trackTargetHint = "Montant maximum en DA",
                trackStart = "Activer le suivi",
                trackNoAccount = "Sans compte. Une adresse, un e-mail de confirmation, et vous pouvez tout arrêter d’un lien.",
                trackSent = "E-mail envoyé à {email}",
                trackSentSub = "Ouvrez le lien de confirmation. Tant qu’il n’est pas ouvert, nous ne surveillons rien et ne vous écrivons plus.",
                trackBadEmail = "Cette adresse n’a pas l’air valide.",
                trackFailed = "Le suivi n’a pas pu être créé. Réessayez.",
                myTracking = "Mes suivis",
                noTracking = "Aucun suivi ici",
                noTrackingSub = "Lancez une recherche, puis touchez « Suivre ce trajet ». Vos suivis apparaîtront ici dès que vous ouvrez le lien reçu par e-mail.",
                openManageLink = "J’ai déjà des suivis",
                pasteManageLink = "Collez le lien « Gérer mes alertes » de votre e-mail",
                linkNotValid = "Ce lien n’est pas valide.",
                stopTracking = "Arrêter",
                newTracking = "Nouveau suivi",
                priceHistory = "{n} derniers jours",
                historyLow = "Le plus bas", historyAverage = "Moyenne", historyHigh = "Le plus haut",
                historyObserved = "Sur {n} jours où un prix a été relevé.",
                historyThin = "Trop peu de relevés pour tracer une courbe.",
                historyNone = "Aucun prix relevé pour ce trajet et cette date.",
                seeTodayOffers = "Voir les offres du jour",
                whenYouSubscribed = "À l’activation : {price}",
                targetSet = "Seuil : {price}",
                bestPrice = "MEILLEUR PRIX",
                seeOffer = "Voir l’offre",
                travellerOne = "1 voyageur",
                travellersMany = "{n} voyageurs",
                airlineOne = "1 compagnie",
                airlinesMany = "{n} compagnies",
                compareSites = "Comparer les sites",
                bookOn = "Réserver sur {site}",
                stopsTwoPlus = "2+", baggage = "Bagages", anyBaggage = "Cabine seule",
                navAccount = "Compte",
                seeDetails = "Voir les détails",
                sitesQuoting = "sur {n} sites",
                onlyOnSite = "sur {site}",
                thisDevice = "Cet appareil",
                thisDeviceSub = "Pas de compte à créer. Vos suivis et vos réglages vivent ici.",
                preferences = "Préférences",
                helpAndInfo = "Aide et informations",
                settingsAndAlerts = "Réglages et notifications",
                settingsAndAlertsSub = "Langue, devise, alertes, données",
            )
            Lang.AR -> Words(
                heroTitle = "كل المواقع. بحث واحد.",
                heroSub = "يبحث قصدة في مواقع الحجز الجزائرية في الوقت نفسه.",
                from = "المغادرة", to = "الوجهة", dates = "التواريخ", travellers = "المسافرون",
                search = "ابحث", roundTrip = "ذهاب وإياب", oneWay = "ذهاب فقط",
                searching = "نبحث عن أفضل سعر", searchingSub = "أربعة مواقع، في الوقت نفسه.",
                resultsCount = "{n} رحلات", cheapestOn = "{site} · الأرخص",
                bagIncluded = "مع حقيبة", bagNone = "بدون حقيبة", seatsShort = "مقاعد: {n}",
                direct = "مباشر", stopsOne = "توقف واحد", stopsMany = "{n} توقفات",
                outbound = "ذهاب", inbound = "إياب", book = "احجز",
                noResultsTitle = "لا توجد رحلات {from} ← {to}",
                noResultsSub = "لا يعرض أي موقع حجز هذا الخط في هذا التاريخ.",
                failedTitle = "لم يكتمل البحث",
                failedSub = "انقطع الاتصال قبل أن تجيب المواقع.",
                retry = "أعد المحاولة", priceBySite = "السعر، موقعًا بموقع", cheapest = "الأرخص",
                economy = "اقتصادية", searchCity = "مدينة أو مطار", noAirport = "لا يوجد مطار مطابق",
                chooseDates = "اختر التواريخ", confirm = "تأكيد", cancel = "إلغاء",
                cabinBag = "حقيبة اليد", checkedBag = "حقيبة مسجلة", bagUnknown = "غير محدد",
                pieces = "{n} قطعة", kilos = "{n} كغ", conditions = "شروط التذكرة",
                refundable = "قابلة للاسترداد", nonRefundable = "غير قابلة للاسترداد",
                changeable = "قابلة للتغيير", nonChangeable = "غير قابلة للتغيير",
                feeApplies = "رسوم {amount}", operatedBy = "تشغيل {airline}",
                adults = "البالغون", adultsAge = "12 سنة فما فوق",
                children = "الأطفال", childrenAge = "2 – 11 سنة",
                infants = "الرضّع", infantsAge = "أقل من سنتين",
                cabinClass = "درجة السفر", premium = "اقتصادية بريميوم",
                business = "رجال الأعمال", first = "الأولى", apply = "تطبيق",
                filters = "عوامل التصفية", sortBy = "ترتيب", sortPrice = "السعر",
                sortDeparture = "المغادرة", sortDuration = "المدة",
                departureTime = "وقت المغادرة", morning = "صباحًا", afternoon = "بعد الظهر",
                evening = "مساءً", night = "ليلًا", maxPrice = "السعر الأقصى",
                reset = "إعادة الضبط", showCount = "عرض {n} رحلات",
                noMatchTitle = "لا توجد رحلة مطابقة",
                noMatchSub = "وسّع عوامل التصفية لرؤية نتائج أكثر.",
                stopsLabel = "التوقفات",
                navHome = "الرئيسية", navHelp = "مساعدة", navSettings = "الإعدادات",
                about = "من نحن", language = "اللغة",
                systemLanguage = "لغة الهاتف",
                howItWorks = "كيف تعمل", privacy = "الخصوصية",
                contactUs = "اكتب لنا", openOnSite = "افتح على الموقع",
                version = "الإصدار", recentSearches = "عمليات بحث أخيرة",
                offline = "لا يوجد اتصال بالإنترنت",
                seatOne = "مقعد واحد", edit = "تعديل",
                priceCalendar = "تقويم الأسعار",
                calendarLoading = "نسأل المواقع عن كل تاريخ. يستغرق هذا لحظة.",
                calendarEmpty = "لا توجد أسعار لهذه الفترة.",
                calendarNote = "كل سعر هنا عرضه موقع لذلك التاريخ. التاريخ بلا سعر هو تاريخ لم يسعّره أي موقع.",
                cheapestDay = "الأرخص: {date} · {price}",
                noPriceThatDay = "لا سعر",
                nearbyDates = "تواريخ قريبة",
                comparing = "نقارن العروض…",
                offersSoFar = "{n} عروض",
                aboutTitle = "من نحن",
                aboutTagline = "مقارنة أسعار الرحلات انطلاقًا من الجزائر",
                aboutWhat = "يسأل قصدة الوكالات الجزائرية مباشرة ويعرض السعر الحقيقي لكل عرض، دون عمولة ولا زيادة.",
                aboutNotTickets = "نحن لا نبيع التذاكر: الحجز يتم دائمًا على موقع الوكالة التي تختارها.",
                readMore = "اقرأ المزيد",
                faq = "أسئلة شائعة",
                cheapestOfSites = "{site} · الأرخص من بين {n} مواقع",
                navTracking = "المتابعة",
                trackRoute = "تابع هذه الرحلة",
                trackTitle = "تابع هذه الرحلة",
                trackSub = "نراقب السعر نيابة عنك.",
                trackEmail = "بريدك الإلكتروني",
                trackEmailHint = "name@example.com",
                trackTarget = "نبّهني إذا نزل تحت (اختياري)",
                trackTargetHint = "أقصى مبلغ بالدينار",
                trackStart = "فعّل المتابعة",
                trackNoAccount = "بدون حساب. عنوان بريد، رسالة تأكيد، ويمكنك إيقاف كل شيء برابط واحد.",
                trackSent = "أُرسلت رسالة إلى {email}",
                trackSentSub = "افتح رابط التأكيد. ما لم تفتحه، لا نراقب شيئًا ولا نراسلك مرة أخرى.",
                trackBadEmail = "هذا العنوان لا يبدو صحيحًا.",
                trackFailed = "تعذّر إنشاء المتابعة. أعد المحاولة.",
                myTracking = "متابعاتي",
                noTracking = "لا توجد متابعات هنا",
                noTrackingSub = "ابحث عن رحلة ثم المس «تابع هذه الرحلة». ستظهر متابعاتك هنا بمجرد فتح الرابط الذي وصلك بالبريد.",
                openManageLink = "لدي متابعات بالفعل",
                pasteManageLink = "الصق رابط «إدارة التنبيهات» من بريدك",
                linkNotValid = "هذا الرابط غير صالح.",
                stopTracking = "أوقف",
                newTracking = "متابعة جديدة",
                priceHistory = "آخر {n} يومًا",
                historyLow = "الأدنى", historyAverage = "المتوسط", historyHigh = "الأعلى",
                historyObserved = "على {n} يومًا سُجّل فيها سعر.",
                historyThin = "السجلات أقل من أن تُرسم منحنى.",
                historyNone = "لا توجد أسعار مسجّلة لهذه الرحلة وهذا التاريخ.",
                seeTodayOffers = "شاهد عروض اليوم",
                whenYouSubscribed = "عند التفعيل: {price}",
                targetSet = "الحد: {price}",
                bestPrice = "أفضل سعر",
                seeOffer = "عرض التفاصيل",
                travellerOne = "مسافر واحد",
                travellersMany = "{n} مسافرين",
                airlineOne = "شركة واحدة",
                airlinesMany = "{n} شركات",
                compareSites = "قارن المواقع",
                bookOn = "احجز على {site}",
                stopsTwoPlus = "+2", baggage = "الأمتعة", anyBaggage = "حقيبة يد فقط",
                navAccount = "الحساب",
                seeDetails = "عرض التفاصيل",
                sitesQuoting = "على {n} مواقع",
                onlyOnSite = "على {site}",
                thisDevice = "هذا الجهاز",
                thisDeviceSub = "لا حاجة لإنشاء حساب. متابعاتك وإعداداتك محفوظة هنا.",
                preferences = "التفضيلات",
                helpAndInfo = "المساعدة والمعلومات",
                settingsAndAlerts = "الإعدادات والإشعارات",
                settingsAndAlertsSub = "اللغة والعملة والتنبيهات والبيانات",
            )
            Lang.EN -> Words(
                heroTitle = "Every site. One search.",
                heroSub = "Qasda queries the Algerian booking sites at the same time.",
                from = "From", to = "To", dates = "Dates", travellers = "Travellers",
                search = "Search", roundTrip = "Round trip", oneWay = "One way",
                searching = "Finding the best price", searchingSub = "Four sites, at once.",
                resultsCount = "{n} flights", cheapestOn = "{site} · cheapest",
                bagIncluded = "Bag included", bagNone = "No checked bag", seatsShort = "{n} seats",
                direct = "Direct", stopsOne = "1 stop", stopsMany = "{n} stops",
                outbound = "Outbound", inbound = "Return", book = "Book",
                noResultsTitle = "No flights {from} → {to}",
                noResultsSub = "No booking site offers this route on this date.",
                failedTitle = "The search did not complete",
                failedSub = "The connection dropped before the sites answered.",
                retry = "Try again", priceBySite = "The price, site by site", cheapest = "cheapest",
                economy = "Economy", searchCity = "City or airport", noAirport = "No matching airport",
                chooseDates = "Choose dates", confirm = "Confirm", cancel = "Cancel",
                cabinBag = "Cabin bag", checkedBag = "Checked bag", bagUnknown = "Not stated",
                pieces = "{n} piece(s)", kilos = "{n} kg", conditions = "Ticket conditions",
                refundable = "Refundable", nonRefundable = "Non-refundable",
                changeable = "Changeable", nonChangeable = "Not changeable",
                feeApplies = "{amount} fee", operatedBy = "Operated by {airline}",
                adults = "Adults", adultsAge = "12 and over",
                children = "Children", childrenAge = "2 – 11",
                infants = "Infants", infantsAge = "under 2",
                cabinClass = "Cabin class", premium = "Premium economy",
                business = "Business", first = "First", apply = "Apply",
                filters = "Filters", sortBy = "Sort", sortPrice = "Price",
                sortDeparture = "Departure", sortDuration = "Duration",
                departureTime = "Departure time", morning = "Morning", afternoon = "Afternoon",
                evening = "Evening", night = "Night", maxPrice = "Maximum price",
                reset = "Reset", showCount = "Show {n} flights",
                noMatchTitle = "No flight matches",
                noMatchSub = "Widen the filters to see more results.",
                stopsLabel = "Stops",
                navHome = "Home", navHelp = "Help", navSettings = "Settings",
                about = "About", language = "Language",
                systemLanguage = "Phone language",
                howItWorks = "How it works", privacy = "Privacy",
                contactUs = "Write to us", openOnSite = "Open on the site",
                version = "Version", recentSearches = "Recent searches",
                offline = "No internet connection",
                seatOne = "1 seat", edit = "Edit",
                priceCalendar = "Price calendar",
                calendarLoading = "Asking the sites about each date. This takes a moment.",
                calendarEmpty = "No prices for these dates.",
                calendarNote = "Every price here is one a site showed for that date. A date with no price is a date no site quoted.",
                cheapestDay = "Cheapest: {date} · {price}",
                noPriceThatDay = "No price",
                nearbyDates = "Nearby dates",
                comparing = "Comparing the offers…",
                offersSoFar = "{n} offers",
                aboutTitle = "About",
                aboutTagline = "Flight prices from Algeria, compared",
                aboutWhat = "Qasda queries the Algerian agencies live and shows the real price of every offer, with no commission and no markup.",
                aboutNotTickets = "We do not sell tickets: the booking always happens on the site of the agency you choose.",
                readMore = "Read more",
                faq = "Frequently asked questions",
                cheapestOfSites = "{site} · cheapest of {n} sites",
                navTracking = "Tracking",
                trackRoute = "Track this route",
                trackTitle = "Track this route",
                trackSub = "We watch the price for you.",
                trackEmail = "Your email address",
                trackEmailHint = "name@example.com",
                trackTarget = "Alert me under (optional)",
                trackTargetHint = "Maximum amount in DA",
                trackStart = "Start tracking",
                trackNoAccount = "No account. One address, one confirmation email, and one link that stops everything.",
                trackSent = "Email sent to {email}",
                trackSentSub = "Open the confirmation link. Until you do we watch nothing and write to you no further.",
                trackBadEmail = "That address does not look right.",
                trackFailed = "The tracking could not be created. Try again.",
                myTracking = "My tracking",
                noTracking = "Nothing tracked here",
                noTrackingSub = "Run a search, then tap “Track this route”. What you track appears here as soon as you open the link in your email.",
                openManageLink = "I already track routes",
                pasteManageLink = "Paste the “Manage my alerts” link from your email",
                linkNotValid = "That link is not valid.",
                stopTracking = "Stop",
                newTracking = "New tracking",
                priceHistory = "Last {n} days",
                historyLow = "Lowest", historyAverage = "Average", historyHigh = "Highest",
                historyObserved = "Over {n} days on which a price was recorded.",
                historyThin = "Too few readings to draw a line.",
                historyNone = "No price recorded for this route and date.",
                seeTodayOffers = "See today’s offers",
                whenYouSubscribed = "When you started: {price}",
                targetSet = "Threshold: {price}",
                bestPrice = "BEST PRICE",
                seeOffer = "See the offer",
                travellerOne = "1 traveller",
                travellersMany = "{n} travellers",
                airlineOne = "1 airline",
                airlinesMany = "{n} airlines",
                compareSites = "Compare the sites",
                bookOn = "Book on {site}",
                stopsTwoPlus = "2+", baggage = "Baggage", anyBaggage = "Cabin bag only",
                navAccount = "Account",
                seeDetails = "See details",
                sitesQuoting = "on {n} sites",
                onlyOnSite = "on {site}",
                thisDevice = "This device",
                thisDeviceSub = "No account to create. Your tracking and settings live here.",
                preferences = "Preferences",
                helpAndInfo = "Help and information",
                settingsAndAlerts = "Settings and notifications",
                settingsAndAlertsSub = "Language, currency, alerts, data",
            )
        }
    }
}
