package pro.qasdatrip.core

/**
 * The words, in the three languages the product speaks. They live in the
 * shared module rather than in Android resources so the iOS app says exactly
 * the same things, and so a string can never exist in one language only.
 */
data class Words(
    val appName: String = "Qasda",
    val heroTitle: String,
    val heroSub: String,
    val from: String,
    val to: String,
    val dates: String,
    val travellers: String,
    val search: String,
    val roundTrip: String,
    val oneWay: String,
    val searching: String,
    val searchingSub: String,
    val resultsCount: String,       // {n}
    val cheapestOn: String,         // {site}
    val bagIncluded: String,
    val bagNone: String,
    val seatsShort: String,         // {n}
    val direct: String,
    val stopsOne: String,
    val stopsMany: String,          // {n}
    val outbound: String,
    val inbound: String,
    val book: String,
    val noResultsTitle: String,     // {from} {to}
    val noResultsSub: String,
    val failedTitle: String,
    val failedSub: String,
    val retry: String,
    val priceBySite: String,
    val cheapest: String,
    val economy: String,
    val searchCity: String,
    val noAirport: String,
    val chooseDates: String,
    val confirm: String,
    val cancel: String,
    val cabinBag: String,
    val checkedBag: String,
    val bagUnknown: String,
    val pieces: String,             // {n}
    val kilos: String,              // {n}
    val conditions: String,
    val refundable: String,
    val nonRefundable: String,
    val changeable: String,
    val nonChangeable: String,
    val feeApplies: String,         // {amount}
    val operatedBy: String,         // {airline}
    val adults: String,
    val adultsAge: String,
    val children: String,
    val childrenAge: String,
    val infants: String,
    val infantsAge: String,
    val cabinClass: String,
    val premium: String,
    val business: String,
    val first: String,
    val apply: String,
    val filters: String,
    val sortBy: String,
    val sortPrice: String,
    val sortDeparture: String,
    val sortDuration: String,
    val departureTime: String,
    val morning: String,
    val afternoon: String,
    val evening: String,
    val night: String,
    val maxPrice: String,
    val reset: String,
    val showCount: String,          // {n}
    val noMatchTitle: String,
    val noMatchSub: String,
    val stopsLabel: String,
) {
    companion object {
        fun of(lang: Lang): Words = when (lang) {
            Lang.FR -> Words(
                heroTitle = "Tous les sites. Une recherche.",
                heroSub = "Qasda interroge les sites de réservation algériens en même temps.",
                from = "Départ", to = "Destination", dates = "Dates", travellers = "Voyageurs",
                search = "Rechercher", roundTrip = "Aller-retour", oneWay = "Aller simple",
                searching = "Nous cherchons le meilleur prix", searchingSub = "Quatre sites, en même temps.",
                resultsCount = "{n} vols", cheapestOn = "{site} · le moins cher",
                bagIncluded = "Bagage inclus", bagNone = "Sans bagage", seatsShort = "{n} places",
                direct = "Direct", stopsOne = "1 escale", stopsMany = "{n} escales",
                outbound = "Aller", inbound = "Retour", book = "Réserver",
                noResultsTitle = "Aucun vol {from} → {to}",
                noResultsSub = "Aucun site de réservation ne propose ce trajet à cette date.",
                failedTitle = "La recherche n’a pas abouti",
                failedSub = "La connexion s’est interrompue avant que les sites répondent.",
                retry = "Réessayer", priceBySite = "Le prix, site par site", cheapest = "le moins cher",
                economy = "Économique", searchCity = "Ville ou aéroport", noAirport = "Aucun aéroport ne correspond",
                chooseDates = "Choisir les dates", confirm = "Confirmer", cancel = "Annuler",
                cabinBag = "Bagage cabine", checkedBag = "Bagage en soute", bagUnknown = "Non communiqué",
                pieces = "{n} pièce(s)", kilos = "{n} kg", conditions = "Conditions du billet",
                refundable = "Remboursable", nonRefundable = "Non remboursable",
                changeable = "Modifiable", nonChangeable = "Non modifiable",
                feeApplies = "{amount} de frais", operatedBy = "Opéré par {airline}",
                adults = "Adultes", adultsAge = "12 ans et plus",
                children = "Enfants", childrenAge = "2 – 11 ans",
                infants = "Bébés", infantsAge = "moins de 2 ans",
                cabinClass = "Classe de cabine", premium = "Économique premium",
                business = "Affaires", first = "Première", apply = "Appliquer",
                filters = "Filtres", sortBy = "Trier", sortPrice = "Prix",
                sortDeparture = "Départ", sortDuration = "Durée",
                departureTime = "Heure de départ", morning = "Matin", afternoon = "Après-midi",
                evening = "Soir", night = "Nuit", maxPrice = "Prix maximum",
                reset = "Réinitialiser", showCount = "Voir {n} vols",
                noMatchTitle = "Aucun vol ne correspond",
                noMatchSub = "Élargissez les filtres pour voir plus de résultats.",
                stopsLabel = "Escales",
            )
            Lang.AR -> Words(
                heroTitle = "كل المواقع. بحث واحد.",
                heroSub = "يبحث قصدة في مواقع الحجز الجزائرية في الوقت نفسه.",
                from = "المغادرة", to = "الوجهة", dates = "التواريخ", travellers = "المسافرون",
                search = "ابحث", roundTrip = "ذهاب وإياب", oneWay = "ذهاب فقط",
                searching = "نبحث عن أفضل سعر", searchingSub = "أربعة مواقع، في الوقت نفسه.",
                resultsCount = "{n} رحلات", cheapestOn = "{site} · الأرخص",
                bagIncluded = "مع حقيبة", bagNone = "بدون حقيبة", seatsShort = "مقاعد: {n}",
                direct = "مباشر", stopsOne = "توقف واحد", stopsMany = "{n} توقفات",
                outbound = "ذهاب", inbound = "إياب", book = "احجز",
                noResultsTitle = "لا توجد رحلات {from} ← {to}",
                noResultsSub = "لا يعرض أي موقع حجز هذا الخط في هذا التاريخ.",
                failedTitle = "لم يكتمل البحث",
                failedSub = "انقطع الاتصال قبل أن تجيب المواقع.",
                retry = "أعد المحاولة", priceBySite = "السعر، موقعًا بموقع", cheapest = "الأرخص",
                economy = "اقتصادية", searchCity = "مدينة أو مطار", noAirport = "لا يوجد مطار مطابق",
                chooseDates = "اختر التواريخ", confirm = "تأكيد", cancel = "إلغاء",
                cabinBag = "حقيبة اليد", checkedBag = "حقيبة مسجلة", bagUnknown = "غير محدد",
                pieces = "{n} قطعة", kilos = "{n} كغ", conditions = "شروط التذكرة",
                refundable = "قابلة للاسترداد", nonRefundable = "غير قابلة للاسترداد",
                changeable = "قابلة للتغيير", nonChangeable = "غير قابلة للتغيير",
                feeApplies = "رسوم {amount}", operatedBy = "تشغيل {airline}",
                adults = "البالغون", adultsAge = "12 سنة فما فوق",
                children = "الأطفال", childrenAge = "2 – 11 سنة",
                infants = "الرضّع", infantsAge = "أقل من سنتين",
                cabinClass = "درجة السفر", premium = "اقتصادية بريميوم",
                business = "رجال الأعمال", first = "الأولى", apply = "تطبيق",
                filters = "عوامل التصفية", sortBy = "ترتيب", sortPrice = "السعر",
                sortDeparture = "المغادرة", sortDuration = "المدة",
                departureTime = "وقت المغادرة", morning = "صباحًا", afternoon = "بعد الظهر",
                evening = "مساءً", night = "ليلًا", maxPrice = "السعر الأقصى",
                reset = "إعادة الضبط", showCount = "عرض {n} رحلات",
                noMatchTitle = "لا توجد رحلة مطابقة",
                noMatchSub = "وسّع عوامل التصفية لرؤية نتائج أكثر.",
                stopsLabel = "التوقفات",
            )
            Lang.EN -> Words(
                heroTitle = "Every site. One search.",
                heroSub = "Qasda queries the Algerian booking sites at the same time.",
                from = "From", to = "To", dates = "Dates", travellers = "Travellers",
                search = "Search", roundTrip = "Round trip", oneWay = "One way",
                searching = "Finding the best price", searchingSub = "Four sites, at once.",
                resultsCount = "{n} flights", cheapestOn = "{site} · cheapest",
                bagIncluded = "Bag included", bagNone = "No checked bag", seatsShort = "{n} seats",
                direct = "Direct", stopsOne = "1 stop", stopsMany = "{n} stops",
                outbound = "Outbound", inbound = "Return", book = "Book",
                noResultsTitle = "No flights {from} → {to}",
                noResultsSub = "No booking site offers this route on this date.",
                failedTitle = "The search did not complete",
                failedSub = "The connection dropped before the sites answered.",
                retry = "Try again", priceBySite = "The price, site by site", cheapest = "cheapest",
                economy = "Economy", searchCity = "City or airport", noAirport = "No matching airport",
                chooseDates = "Choose dates", confirm = "Confirm", cancel = "Cancel",
                cabinBag = "Cabin bag", checkedBag = "Checked bag", bagUnknown = "Not stated",
                pieces = "{n} piece(s)", kilos = "{n} kg", conditions = "Ticket conditions",
                refundable = "Refundable", nonRefundable = "Non-refundable",
                changeable = "Changeable", nonChangeable = "Not changeable",
                feeApplies = "{amount} fee", operatedBy = "Operated by {airline}",
                adults = "Adults", adultsAge = "12 and over",
                children = "Children", childrenAge = "2 – 11",
                infants = "Infants", infantsAge = "under 2",
                cabinClass = "Cabin class", premium = "Premium economy",
                business = "Business", first = "First", apply = "Apply",
                filters = "Filters", sortBy = "Sort", sortPrice = "Price",
                sortDeparture = "Departure", sortDuration = "Duration",
                departureTime = "Departure time", morning = "Morning", afternoon = "Afternoon",
                evening = "Evening", night = "Night", maxPrice = "Maximum price",
                reset = "Reset", showCount = "Show {n} flights",
                noMatchTitle = "No flight matches",
                noMatchSub = "Widen the filters to see more results.",
                stopsLabel = "Stops",
            )
        }
    }
}
